### ISSUE TITLE
Command not found coveralls

### ISSUE THREAD

**Issue by devdazed** [z4r/python-coveralls#28]
I used your readme to set up my coveralls for travis and it keeps getting the following error:

```
$ coveralls
/home/travis/build.sh: line 41: coveralls: command not found
```

the relevant lines from my travis.yml:

``` yaml
install:
  - pip install --upgrade setuptools
  - pip install python-coveralls
  - pip install -r requirements.txt

script: 
  - nosetests --with-coverage --cover-package=app --cov-report term-missing

after_success:
  - coveralls
```

I also get a command not found when trying to pip install it on my local host.
